### ISSUE TITLE
Instalar leila a través de Conda

### ISSUE THREAD

**Issue by dersteppenwolf** [ucd-dnp/leila#3]
Buen día

Sería posible que adicionaran la opción de instalar la librería utilizando conda?

por ejemplo con el comando

conda install -c conda-forge leila

**Comment by pablomonhel** [comment]
Buenas tardes, 

En este momento estamos trabajando para que la librería LEILA pueda ser instalada en Anaconda con el comando "conda install". En todo caso, puede ser instalada con el comando "pip install leila" en la consola de Anaconda. 

Avisaremos sobre cualquier novedad al respecto

Cordial saludo

Unidad de Científicos de Datos del DNP

**Comment by pablomonhel** [comment]
Buenos días, 

Es posible ahora instalar LEILA en Anaconda de la siguiente manera:

    conda install -c ucd-dnp leila

Cordial saludo

Unidad de Científicos de Datos del DNP
